wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.7
    start_time: 1666535037.263553
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.7
      5: 0.13.4
      6: 4.20.1
      8:
      - 1
      - 2
      - 3
      - 5
